# Generated by Django 4.2.1 on 2023-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gloriaDemos', '0002_user_is_administrador_user_is_operador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/media/user.png', upload_to='media/'),
        ),
    ]
