# Generated by Django 4.2.1 on 2023-06-19 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gloriaDemos', '0003_alter_control_cont_neto_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_cont_neto',
            name='hora_reg',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='control_cont_neto',
            name='promedio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='control_cont_neto',
            name='rango',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
