# Generated by Django 4.2.1 on 2023-06-22 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gloriaDemos', '0005_control_cont_neto_cilindro1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_cont_neto',
            name='operador',
            field=models.ForeignKey(limit_choices_to={'is_operador': True}, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='control_cont_neto',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'is_supervisor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones', to=settings.AUTH_USER_MODEL),
        ),
    ]
